// Copyright (c) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Npcf_UEPolicyControl

UE Policy Control Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Generated by: OpenAPI Generator (https://openapi-generator.tech)
*/

package uepolicy

import (
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/omec-project/pcf/logger"
)

// Delete /policies/:polAssoId
// Delete individual UE policy association.
func HTTPDeleteIndividualUEPolicyAssociation(c *gin.Context) {
	logger.HandlerLog.Warnln("Handle Delete /policies/:polAssoId is not implemented")
	c.String(http.StatusNotImplemented, "501 not implemented")
}

// Get /policies/:polAssoId
// Read individual UE policy association.
func HTTPReadIndividualUEPolicyAssociation(c *gin.Context) {
	logger.HandlerLog.Warnln("Handle Get /policies/:polAssoId is not implemented")
	c.String(http.StatusNotImplemented, "501 not implemented")
}

// Post /policies/:polAssoId/update
// Report observed event triggers and possibly obtain updated policies for an individual UE policy association.
func HTTPReportObservedEventTriggersForIndividualUEPolicyAssociation(c *gin.Context) {
	logger.HandlerLog.Warnln("Handle Post /policies/:polAssoId/update is not implemented")
	c.String(http.StatusNotImplemented, "501 not implemented")
}
