// Copyright (c) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Npcf_UEPolicyControl

UE Policy Control Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Generated by: OpenAPI Generator (https://openapi-generator.tech)
*/

package uepolicy

import (
	"github.com/gin-gonic/gin"
	"github.com/omec-project/pcf/logger"
)

// Post /policies
// Create individual UE policy association.
func HTTPCreateIndividualUEPolicyAssociation(c *gin.Context) {
	detail := "Handle Post /policies is not implemented"
	logger.HandlerLog.Warnln(detail)
	writeNotImplementedProblem(c, detail)
}
