// SPDX-FileCopyrightText: 2021 Open Networking Foundation <info@opennetworking.org>
//
// SPDX-License-Identifier: Apache-2.0
// SPDX-License-Identifier: LicenseRef-ONF-Member-Only-1.0

/*
 * Npcf_UEPolicyControl
 *
 * UE Policy Control Service API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package uepolicy

import (
	"github.com/gin-gonic/gin"
)

// PoliciesPolAssoIdDelete -
func PoliciesPolAssoIdDelete(c *gin.Context) {
}

// PoliciesPolAssoIdGet -
func PoliciesPolAssoIdGet(c *gin.Context) {
}

// PoliciesPolAssoIdUpdatePost -
func PoliciesPolAssoIdUpdatePost(c *gin.Context) {
}

// PoliciesPost -
func PoliciesPost(c *gin.Context) {
}
