// Copyright (c) 2026 Intel Corporation
// Copyright 2019 free5GC.org
// SPDX-License-Identifier: Apache-2.0

/*
Npcf_SMPolicyControl API

Session Management Policy Control Service
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Generated by: OpenAPI Generator (https://openapi-generator.tech)
*/

package smpolicy

import (
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/omec-project/openapi/v2"
	"github.com/omec-project/openapi/v2/models"
	"github.com/omec-project/openapi/v2/utils"
	"github.com/omec-project/pcf/logger"
	"github.com/omec-project/pcf/producer"
	"github.com/omec-project/util/httpwrapper"
)

// Post /sm-policies/:smPolicyId/delete
// Delete an existing Individual SM Policy.
func HTTPDeleteSMPolicy(c *gin.Context) {
	logger.SMpolicylog.Infoln("Handle Post /sm-policies/:smPolicyId/delete")
	req := httpwrapper.NewRequest(c.Request, nil)
	req.Params["smPolicyId"] = c.Params.ByName("smPolicyId")

	rsp := producer.HandleDeleteSmPolicyContextRequest(req)

	responseBody, err := openapi.SetBody(rsp.Body, "application/json")
	if err != nil {
		logger.SMpolicylog.Errorln(err)
		problemDetails := utils.ProblemDetailsSystemFailure(err.Error())
		c.JSON(http.StatusInternalServerError, problemDetails)
	} else {
		c.Data(rsp.Status, "application/json", responseBody.Bytes())
	}
}

// Get /sm-policies/:smPolicyId
// Read an Individual SM Policy
func HTTPGetSMPolicy(c *gin.Context) {
	logger.SMpolicylog.Infoln("Handle Get /sm-policies/:smPolicyId")
	req := httpwrapper.NewRequest(c.Request, nil)
	req.Params["smPolicyId"] = c.Params.ByName("smPolicyId")

	rsp := producer.HandleGetSmPolicyContextRequest(req)

	responseBody, err := openapi.SetBody(rsp.Body, "application/json")
	if err != nil {
		logger.SMpolicylog.Errorln(err)
		problemDetails := utils.ProblemDetailsSystemFailure(err.Error())
		c.JSON(http.StatusInternalServerError, problemDetails)
	} else {
		c.Data(rsp.Status, "application/json", responseBody.Bytes())
	}
}

// Post /sm-policies/:smPolicyId/update
// Update an existing Individual SM Policy
func HTTPUpdateSMPolicy(c *gin.Context) {
	logger.SMpolicylog.Infoln("Handle Post /sm-policies/:smPolicyId/update")
	var smPolicyUpdateContextData models.SmPolicyUpdateContextData
	// step 1: retrieve http request body
	requestBody, err := c.GetRawData()
	if err != nil {
		problemDetail := utils.ProblemDetailsSystemFailure(err.Error())
		logger.SMpolicylog.Errorf("Get Request Body error: %+v", err)
		c.JSON(http.StatusInternalServerError, problemDetail)
		return
	}

	// step 2: convert requestBody to openapi models
	err = openapi.Decode(&smPolicyUpdateContextData, requestBody, "application/json")
	if err != nil {
		problemDetail := "[Request Body] " + err.Error()
		rsp := utils.ProblemDetailsMalformedRequestSyntax(problemDetail)
		logger.SMpolicylog.Errorln(problemDetail)
		c.JSON(http.StatusBadRequest, rsp)
		return
	}

	req := httpwrapper.NewRequest(c.Request, smPolicyUpdateContextData)
	req.Params["smPolicyId"] = c.Params.ByName("smPolicyId")

	rsp := producer.HandleUpdateSmPolicyContextRequest(req)

	responseBody, err := openapi.SetBody(rsp.Body, "application/json")
	if err != nil {
		logger.SMpolicylog.Errorln(err)
		problemDetails := utils.ProblemDetailsSystemFailure(err.Error())
		c.JSON(http.StatusInternalServerError, problemDetails)
	} else {
		c.Data(rsp.Status, "application/json", responseBody.Bytes())
	}
}
