// Copyright (c) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Npcf_SMPolicyControl API

Session Management Policy Control Service
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Generated by: OpenAPI Generator (https://openapi-generator.tech)
*/

package smpolicy

import (
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/omec-project/pcf/logger"
)

// Post /:$request.body#/notificationUri/terminate
func HTTPSmPolicyControlTerminationRequestNotificationTerminatePost(c *gin.Context) {
	logger.SMpolicylog.Warnln("Handle Post /:$request.body#/notificationUri/terminate is not implemented")
	c.String(http.StatusNotImplemented, "501 not implemented")
}
