// Copyright (c) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Npcf_AMPolicyControl

Access and Mobility Policy Control Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.5

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Generated by: OpenAPI Generator (https://openapi-generator.tech)
*/

package ampolicy

import (
	"github.com/gin-gonic/gin"
	"github.com/omec-project/pcf/logger"
)

// Post /:$request.body#/notificationUri/update
func HTTPPolicyUpdateNotificationUpdatePost(c *gin.Context) {
	detail := "Handle Post /:$request.body#/notificationUri/update is not implemented"
	logger.AMpolicylog.Warnln(detail)
	writeNotImplementedProblem(c, detail)
}
