// Copyright (c) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Npcf_BDTPolicyControl Service API

PCF BDT Policy Control Service.
© 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.1

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Generated by: OpenAPI Generator (https://openapi-generator.tech)
*/

package bdtpolicy

import (
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/omec-project/pcf/logger"
)

// Post /:$request.body#/notifUri
func HTTPBdtNotificationPost(c *gin.Context) {
	logger.Bdtpolicylog.Warnln("Handle Post /:$request.body#/notifUri is not implemented")
	c.String(http.StatusNotImplemented, "501 not implemented")
}
