// Copyright (c) 2026 Intel Corporation
// Copyright 2019 free5GC.org
// SPDX-License-Identifier: Apache-2.0

/*
Npcf_PolicyAuthorization Service API

PCF Policy Authorization Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Generated by: OpenAPI Generator (https://openapi-generator.tech)
*/

package policyauthorization

import (
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/omec-project/openapi/v2"
	"github.com/omec-project/openapi/v2/models"
	"github.com/omec-project/openapi/v2/utils"
	"github.com/omec-project/pcf/logger"
	"github.com/omec-project/pcf/producer"
	"github.com/omec-project/pcf/util"
	"github.com/omec-project/util/httpwrapper"
)

// Delete /app-sessions/:appSessionId/events-subscription
// deletes the Events Subscription subresource
func HTTPDeleteEventsSubsc(c *gin.Context) {
	logger.PolicyAuthorizationlog.Infoln("Handle Delete /app-sessions/:appSessionId/events-subscription")
	req := httpwrapper.NewRequest(c.Request, nil)
	req.Params["appSessionId"], _ = c.Params.Get("appSessionId")

	rsp := producer.HandleDeleteEventsSubscContext(req)

	responseBody, err := openapi.SetBody(rsp.Body, "application/json")
	if err != nil {
		logger.PolicyAuthorizationlog.Errorln(err)
		problemDetails := utils.ProblemDetailsSystemFailure(err.Error())
		c.JSON(http.StatusInternalServerError, problemDetails)
	} else {
		c.Data(rsp.Status, "application/json", responseBody.Bytes())
	}
}

// Put /app-sessions/:appSessionId/events-subscription
// creates or modifies an Events Subscription subresource
func HTTPUpdateEventsSubsc(c *gin.Context) {
	logger.PolicyAuthorizationlog.Infoln("Handle Put /app-sessions/:appSessionId/events-subscription")
	var eventsSubscReqData models.EventsSubscReqData

	requestBody, err := c.GetRawData()
	if err != nil {
		problemDetail := utils.ProblemDetailsSystemFailure(err.Error())
		logger.PolicyAuthorizationlog.Errorf("Get Request Body error: %+v", err)
		c.JSON(http.StatusInternalServerError, problemDetail)
		return
	}

	err = openapi.Decode(&eventsSubscReqData, requestBody, "application/json")
	if err != nil {
		problemDetail := "[Request Body] " + err.Error()
		rsp := utils.ProblemDetailsMalformedRequestSyntax(problemDetail)
		logger.PolicyAuthorizationlog.Errorln(problemDetail)
		c.JSON(http.StatusBadRequest, rsp)
		return
	}

	if eventsSubscReqData.Events == nil || eventsSubscReqData.GetNotifUri() == "" {
		problemDetail := util.GetProblemDetail("Erroneous/Missing mandatory IE", util.ERROR_REQUEST_PARAMETERS)
		logger.PolicyAuthorizationlog.Errorln(problemDetail.GetDetail())
		c.JSON(int(problemDetail.GetStatus()), problemDetail)
		return
	}

	req := httpwrapper.NewRequest(c.Request, eventsSubscReqData)
	req.Params["appSessionId"], _ = c.Params.Get("appSessionId")

	rsp := producer.HandleUpdateEventsSubscContext(req)

	responseBody, err := openapi.SetBody(rsp.Body, "application/json")
	if err != nil {
		logger.PolicyAuthorizationlog.Errorln(err)
		problemDetails := utils.ProblemDetailsSystemFailure(err.Error())
		c.JSON(http.StatusInternalServerError, problemDetails)
	} else {
		c.Data(rsp.Status, "application/json", responseBody.Bytes())
	}
}
