// Copyright (c) 2026 Intel Corporation
// Copyright 2019 free5GC.org
// SPDX-License-Identifier: Apache-2.0

/*
Npcf_PolicyAuthorization Service API

PCF Policy Authorization Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Generated by: OpenAPI Generator (https://openapi-generator.tech)
*/

package policyauthorization

import (
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/omec-project/openapi/v2"
	"github.com/omec-project/openapi/v2/models"
	"github.com/omec-project/openapi/v2/utils"
	"github.com/omec-project/pcf/logger"
	"github.com/omec-project/pcf/producer"
	"github.com/omec-project/pcf/util"
	"github.com/omec-project/util/httpwrapper"
)

// Post /app-sessions
// Creates a new Individual Application Session Context resource
func HTTPPostAppSessions(c *gin.Context) {
	logger.PolicyAuthorizationlog.Infoln("Handle Post /app-sessions")
	var appSessionContext models.AppSessionContext

	requestBody, err := c.GetRawData()
	if err != nil {
		problemDetail := utils.ProblemDetailsSystemFailure(err.Error())
		logger.PolicyAuthorizationlog.Errorf("Get Request Body error: %+v", err)
		c.JSON(http.StatusInternalServerError, problemDetail)
		return
	}

	err = openapi.Decode(&appSessionContext, requestBody, "application/json")
	if err != nil {
		problemDetail := "[Request Body] " + err.Error()
		rsp := utils.ProblemDetailsMalformedRequestSyntax(problemDetail)
		logger.PolicyAuthorizationlog.Errorln(problemDetail)
		c.JSON(http.StatusBadRequest, rsp)
		return
	}

	ascReqData := appSessionContext.AscReqData
	if ascReqData.Get() == nil || ascReqData.Get().SuppFeat == "" || ascReqData.Get().NotifUri == "" {
		// Check Mandatory IEs
		rsp := util.GetProblemDetail("Erroneous/Missing mandatory IE", util.ERROR_INITIAL_PARAMETERS)
		logger.PolicyAuthorizationlog.Errorln(rsp.GetDetail())
		c.JSON(int(rsp.GetStatus()), rsp)
		return
	}

	req := httpwrapper.NewRequest(c.Request, appSessionContext)
	rsp := producer.HandlePostAppSessionsContext(req)

	for key, val := range rsp.Header {
		c.Header(key, val[0])
	}
	responseBody, err := openapi.SetBody(rsp.Body, "application/json")
	if err != nil {
		logger.PolicyAuthorizationlog.Errorln(err)
		problemDetails := utils.ProblemDetailsSystemFailure(err.Error())
		c.JSON(http.StatusInternalServerError, problemDetails)
	} else {
		c.Data(rsp.Status, "application/json", responseBody.Bytes())
	}
}
