// Copyright (c) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Npcf_PolicyAuthorization Service API

PCF Policy Authorization Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Generated by: OpenAPI Generator (https://openapi-generator.tech)
*/

package policyauthorization

import (
	"github.com/gin-gonic/gin"
	"github.com/omec-project/pcf/logger"
)

// Post /app-sessions/pcscf-restoration
// Indicates P-CSCF restoration and does not create an Individual Application Session Context
func HTTPPcscfRestoration(c *gin.Context) {
	detail := "Handle Post /app-sessions/pcscf-restoration is not implemented"
	logger.PolicyAuthorizationlog.Warnln(detail)
	writeNotImplementedProblem(c, detail)
}
